blank_issues_enabled: false
contact_links:
  - name: Report a Bug
    url: https://github.com/ElementalDB/issues/new?template=bug_report.md
    about: Create a bug report to help us fix issues.
  - name: Request a Feature
    url: https://github.com/ElementalDB/issues/new?template=feature_request.md
    about: Suggest a new feature for the project.
